version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - pip install pylint
      - pip install pylint-exit
      - pip install bandit
      - pylint lambdacode --max-line-length=400 || pylint-exit $?
      - bandit -r lambdacode -ll --exit-zero

  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip lambdacode
  post_build:
    commands:
      - echo "Updating lambda Function..."