version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install pylint
      - pip install bandit
      - bandit helloworld.py
      - pylint helloworld.py
      

  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip LambdaCode
  post_build:
    commands:
      - echo "Updating lambda Function..."